name: Publish to DOCR

on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCR_USERNAME }}
          password: ${{ secrets.DOCR_PASSWORD }}

      - name: Set environment variables
        run: |
          echo "${{ vars.DEV_PARAMS }}" | tr ' ' '\n' >> .env
          echo TON_CENTER_API_KEY=${{ secrets.DEV_TON_CENTER_API_KEY }} >> .env

      - name: Build and push Docker image
        run: |
          docker build -t registry.digitalocean.com/rsquad-dev/ton-teleport-btc-oracle:latest .
          docker push registry.digitalocean.com/rsquad-dev/ton-teleport-btc-oracle:latest